export { default as Table } from './table/Table'
export { default as Card } from './card/Card'
export { default as IconFile } from './icons/IconFile'
export { default as InputFile } from './inputFile/InputFile'
export { default as Spinner } from './spinner/Spinner'
export { default as Tabs } from './tabs/Tabs'
